apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-with-loadbalancer
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

  selector:
    app: wordpress
